
## CREATING THE PDB

CREATE PLUGGABLE DATABASE WED_27842_Collins_smarttoll_db
Admin User admin IDENTIFIED BY Collins
FILE_NAME_CONVERT=('C:\USERS\HELLO\DOWNLOADS\ORADATA\ORCL\PDBSEED\','C:\USERS\HELLO\DOWNLOADS\ORADATA\ORCL\WED_27842_mutinda_smarttoll_db\');

## ALTERING PDB FOR EDITING

ALTER PLUGGABLE DATABASE WED_27842_Collins_smarttoll_db OPEN; 

##SAVING CONFIGS 

ALTER PLUGGABLE DATABASE WED_27842_Collins_smarttoll_db SAVE STATE;
commit;
--
##CREATING TABLESPACES

##** 1.Toll Data Tablespace
ALTER SESSION SET CONTAINER = WED_27842_Collins_smarttoll_db;
CREATE TABLESPACE toll_data
DATAFILE 'C:/USERS/HELLO/DOWNLOADS/ORADATA/ORCL/WED_27842_Collins_smarttoll_db/toll_data01.dbf'
SIZE 300M
AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED;

##** 2.Toll Index Tablespace
CREATE TABLESPACE toll_index
DATAFILE 'C:/USERS/HELLO/DOWNLOADS/ORADATA/ORCL/WED_27842_Collins_smarttoll_db/toll_index01.dbf'
SIZE 150M
AUTOEXTEND ON NEXT 30M MAXSIZE UNLIMITED;

##** 3.Toll temp Tablespace

 CREATE TEMPORARY TABLESPACE toll_temp
  2  TEMPFILE 'C:/USERS/HELLO/DOWNLOADS/ORADATA/ORCL/WED_27842_Collins_smarttoll_db/toll_temp01.dbf'
  3  SIZE 100M
  4  AUTOEXTEND ON NEXT 20M MAXSIZE UNLIMITED;
--
##CREATING USERS

##**1.Toll_admin

ALTER SESSION SET CONTAINER = WED_27842_Collins_smarttoll_db;
CREATE USER toll_admin IDENTIFIED BY collins
DEFAULT TABLESPACE toll_data
TEMPORARY TABLESPACE toll_temp
QUOTA UNLIMITED ON toll_data;

**GRANTING ACCESS TO DB
 GRANT CONNECT, RESOURCE, DBA TO toll_admin;

##**2.Toll Owner
CREATE USER toll_owner IDENTIFIED BY collins
DEFAULT TABLESPACE toll_data
TEMPORARY TABLESPACE toll_temp
QUOTA UNLIMITED ON toll_data;

**GRANTING ACCESS
GRANT CONNECT, RESOURCE, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
CREATE PROCEDURE, CREATE TRIGGER TO toll_owner;

--
##**TABLE CREATION

ALTER SESSION SET CURRENT_SCHEMA = toll_owner;

##**VEHICLES TABLE

CREATE TABLE vehicles (
    vehicle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number VARCHAR2(20) NOT NULL UNIQUE,
    owner_name VARCHAR2(100) NOT NULL,
    vehicle_type VARCHAR2(30) CHECK (vehicle_type IN ('Sedan','SUV','Truck','Bus','Motorcycle','Van')),
    registration_date DATE DEFAULT SYSDATE
);

##** TOLL GATES TABLE

CREATE TABLE toll_gates (
    gate_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location VARCHAR2(100) NOT NULL,
    road_name VARCHAR2(50) NOT NULL,
    lane_count NUMBER CHECK (lane_count > 0)
);

##** TOLL LOGS TABLE

CREATE TABLE toll_logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id NUMBER NOT NULL,
    gate_id NUMBER NOT NULL,
    entry_time DATE DEFAULT SYSDATE,
    exit_time DATE,
    payment_status VARCHAR2(20) CHECK (payment_status IN ('PAID','UNPAID','PENDING')),
    CONSTRAINT fk_log_vehicle FOREIGN KEY (vehicle_id)
    REFERENCES vehicles(vehicle_id),
    CONSTRAINT fk_log_gate FOREIGN KEY (gate_id)
    REFERENCES toll_gates(gate_id)
);

##** VEHICLE FINES TABLE 

CREATE TABLE vehicle_fine (
    fine_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id NUMBER NOT NULL,
    fine_amount NUMBER(10,2) CHECK (fine_amount >= 0),
    violation_type VARCHAR2(100) NOT NULL,
    violation_date DATE DEFAULT SYSDATE,
    fine_status VARCHAR2(20) CHECK (fine_status IN ('PAID','UNPAID','WAIVED')),
    CONSTRAINT fk_fine_vehicle FOREIGN KEY (vehicle_id)
    REFERENCES vehicles(vehicle_id)
);

##** PAYMENTS TABLE

CREATE TABLE payments (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id NUMBER NOT NULL,
    amount NUMBER(10,2) CHECK (amount >= 0),
    payment_type VARCHAR2(20) CHECK (payment_type IN ('FINE','TOLL')),
    payment_date DATE DEFAULT SYSDATE,
    reference_no VARCHAR2(50) UNIQUE,
    CONSTRAINT fk_payment_vehicle FOREIGN KEY (vehicle_id)
    REFERENCES vehicles(vehicle_id)
);

##**Holidays Table 
 
 CREATE TABLE holidays (
    holiday_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_name VARCHAR2(100),
    holiday_date DATE UNIQUE NOT NULL
);

##** Audit Logs table
CREATE TABLE audit_log (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR2(50),
    operation VARCHAR2(20),
    changed_by VARCHAR2(50),
    old_data VARCHAR2(4000),
    new_data VARCHAR2(4000),
    change_date DATE DEFAULT SYSDATE
);


##** CREATING INDEXES

CREATE INDEX idx_vehicle_plate ON vehicles(plate_number);
CREATE INDEX idx_log_vehicle ON toll_logs(vehicle_id);
CREATE INDEX idx_log_gate ON toll_logs(gate_id);
CREATE INDEX idx_fine_vehicle ON vehicle_fine(vehicle_id);
CREATE INDEX idx_payment_vehicle ON payments(vehicle_id);
